### ISSUE TITLE
Cannot find "pre_train.py"

### ISSUE THREAD

**Issue by erving666** [zmy-9/MF-DAKT#1]

**Comment by erving666** [comment]
Another issue shown when I tried to run ”python3 main.py".
Here's the detail:

2 root error(s) found.
  (0) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory [[node save_1/RestoreV2 (defined at /home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py:418)]]

`student_nums=5002, question_nums=10779, concept_max_nums=188
Data loaded successfully-----
Data is splitted successfully-----
2021-12-13 20:47:37.548513: W tensorflow/core/common_runtime/graph_constructor.cc:1511] Importing a graph with a lower producer version 38 into an existing graph with producer version 898. Shape inference will have run different parts of the graph with different producer versions.
2021-12-13 20:47:37.748256: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-13 20:47:38.170830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7438 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:21:00.0, compute capability: 7.5
2021-12-13 20:47:38.223467: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at save_restore_v2_ops.cc:207 : NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
The max length of skill is:  7
student_nums=5002, question_nums=10779, concept_max_nums=188
Data loaded successfully-----
Data is splitted successfully-----
Traceback (most recent call last):
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1380, in _do_call
    return fn(*args)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1363, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1456, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[{{node save_1/RestoreV2}}]]
	 [[save_1/RestoreV2/_9]]
  (1) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[{{node save_1/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1404, in restore
    sess.run(self.saver_def.restore_op_name,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 970, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1193, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1373, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1399, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[node save_1/RestoreV2
 (defined at /home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py:418)
]]
	 [[save_1/RestoreV2/_9]]
  (1) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[node save_1/RestoreV2
 (defined at /home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py:418)
]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node save_1/RestoreV2:
In[0] save_1/Const:	
In[1] save_1/RestoreV2/tensor_names:	
In[2] save_1/RestoreV2/shape_and_slices:

Operation defined at: (most recent call last)
>>>   File "main.py", line 150, in <module>
>>>     model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
>>>     self._init_graph()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
>>>     self.weights, self.weights2, self.weights3 = self._initialize_weights()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
>>>     weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
>>> 

Input Source operations connected to node save_1/RestoreV2:
In[0] save_1/Const:	
In[1] save_1/RestoreV2/tensor_names:	
In[2] save_1/RestoreV2/shape_and_slices:

Operation defined at: (most recent call last)
>>>   File "main.py", line 150, in <module>
>>>     model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
>>>     self._init_graph()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
>>>     self.weights, self.weights2, self.weights3 = self._initialize_weights()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
>>>     weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
>>> 

Original stack trace for 'save_1/RestoreV2':
  File "main.py", line 150, in <module>
    model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
    self._init_graph()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
    self.weights, self.weights2, self.weights3 = self._initialize_weights()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
    weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1569, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1590, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/meta_graph.py", line 801, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 552, in new_func
    return func(*args, **kwargs)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 407, in import_graph_def
    return _import_graph_def_internal(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 520, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 251, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3847, in _add_new_tf_operations
    new_ops = [
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3848, in <listcomp>
    self._create_op_from_tf_operation(c_op, compute_device=compute_devices)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3730, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2101, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 70, in get_tensor
    return CheckpointReader.CheckpointReader_GetTensor(
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1415, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1736, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 75, in get_tensor
    error_translator(e)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 150, in <module>
    model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
    self._init_graph()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
    self.weights, self.weights2, self.weights3 = self._initialize_weights()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 423, in _initialize_weights
    weight_saver.restore(sess, pretrain_file)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1420, in restore
    raise _wrap_restore_error_with_msg(
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[node save_1/RestoreV2
 (defined at /home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py:418)
]]
	 [[save_1/RestoreV2/_9]]
  (1) NOT_FOUND: ednet/pre_train/problem_embedding_inner_diff_128dims.data-00000-of-00001; No such file or directory
	 [[node save_1/RestoreV2
 (defined at /home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py:418)
]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node save_1/RestoreV2:
In[0] save_1/Const:	
In[1] save_1/RestoreV2/tensor_names:	
In[2] save_1/RestoreV2/shape_and_slices:

Operation defined at: (most recent call last)
>>>   File "main.py", line 150, in <module>
>>>     model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
>>>     self._init_graph()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
>>>     self.weights, self.weights2, self.weights3 = self._initialize_weights()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
>>>     weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
>>> 

Input Source operations connected to node save_1/RestoreV2:
In[0] save_1/Const:	
In[1] save_1/RestoreV2/tensor_names:	
In[2] save_1/RestoreV2/shape_and_slices:

Operation defined at: (most recent call last)
>>>   File "main.py", line 150, in <module>
>>>     model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
>>>     self._init_graph()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
>>>     self.weights, self.weights2, self.weights3 = self._initialize_weights()
>>> 
>>>   File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
>>>     weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
>>> 

Original stack trace for 'save_1/RestoreV2':
  File "main.py", line 150, in <module>
    model = MF_DAKT.MF_DAKT(num_student, num_question, num_concept, args, length, logger)
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 81, in __init__
    self._init_graph()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 123, in _init_graph
    self.weights, self.weights2, self.weights3 = self._initialize_weights()
  File "/home/yuwei/Studio/KT/MF-DAKT/my_project_v2/MF_DAKT.py", line 418, in _initialize_weights
    weight_saver = tf.compat.v1.train.import_meta_graph(pretrain_file + '.meta')
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1569, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1590, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/meta_graph.py", line 801, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 552, in new_func
    return func(*args, **kwargs)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 407, in import_graph_def
    return _import_graph_def_internal(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 520, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 251, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3847, in _add_new_tf_operations
    new_ops = [
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3848, in <listcomp>
    self._create_op_from_tf_operation(c_op, compute_device=compute_devices)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3730, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2101, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

`

**Comment by zmy-9** [comment]
Hi, you can run the pre_question.py to obtain files of pre-train.

**Comment by codingchild2424** [comment]
Then, does 'pre_train.py' not need for implementation? Your README explained the 'pre_train.py'.
